### ISSUE TITLE
Maximum number of connections exceeded

### ISSUE THREAD

**Issue by monocongo** [monocongo/ingest_nclimgrid#10]
When verifying results of an ingest I have come across a maximum number of connections error, perhaps due to resource restrictions on the NOAA FTP server? For example:
```
--- Logging error ---
Traceback (most recent call last):
  File "/home/james/git/ingest_nclimgrid/nclimgrid_ingest.py", line 465, in ingest_nclimgrid
    ftp_files_within_range = find_files_within_range(arguments["date_start"], arguments["date_end"])
  File "/home/james/git/ingest_nclimgrid/nclimgrid_ingest.py", line 43, in find_files_within_range
    with ftplib.FTP(host=_NCLIMGRID_FTP_URL) as ftp:
  File "/home/james/miniconda3/envs/climate/lib/python3.7/ftplib.py", line 117, in __init__
    self.connect(host)
  File "/home/james/miniconda3/envs/climate/lib/python3.7/ftplib.py", line 155, in connect
    self.welcome = self.getresp()
  File "/home/james/miniconda3/envs/climate/lib/python3.7/ftplib.py", line 246, in getresp
    raise error_perm(resp)
ftplib.error_perm: 530 Maximum number of connections exceeded.
```
We'll instead perform an ingest for each variable serially rather than in parallel using multiprocessing and see if that works better (though it will almost certainly be slower).

**Comment by monocongo** [comment]
Resolved by PR #11
